In [1]:
import pandas as pd
import numpy as np

In [2]:
df_origin = pd.read_csv('df_origin.csv', index_col=0)

df = df_origin.copy()
# 컬럼명 변경
df = df.rename(columns={'EXAMIN_BEGIN_DE':'date', 
                    'SEXDSTN_FLAG_CD': 'gender',
                    'AGRDE_FLAG_NM': 'age',
                    'ANSWRR_OC_AREA_NM': 'area',
                    'HSHLD_INCOME_DGREE_NM': 'income',
                    'WORKDAY_DAY_AVRG_LSR_TIME_VALUE': 'lsr_work',
                    'WKEND_DAY_AVRG_LSR_TIME_VALUE': 'lsr_weekend',
                    'ONE_WEEK_TOT_LSR_TIME_VALUE': 'lsr_tot',
                    'LSR_TIME_REST_RCRT_USE_RATE': 'rest',
                    'LSR_TIME_HOBBY_USE_RATE': 'hobby',
                    'LSR_TIME_SELF_IMPT_USE_RATE': 'self',
                    'LSR_TIME_TWDPSN_RLTN_FLWSP_USE_RATE': 'relation',
                    'LSR_TIME_ETC_USE_RATE': 'etc'
                    })
# 조사날짜 컬럼 타입변경
df['date'] = pd.to_datetime(df['date'], format='%Y%m%d').dt.strftime('%Y-%m-%d')

In [3]:
df_origin

RESPOND_ID  EXAMIN_BEGIN_DE SEXDSTN_FLAG_CD AGRDE_FLAG_NM  \
0            3013         20220105               F           50대   
1            3183         20220105               M           60대   
2            5989         20220105               F           30대   
3            6742         20220105               M           50대   
4            9242         20220105               F           30대   
...           ...              ...             ...           ...   
22762    53376818         20221102               F           50대   
22763    53376835         20221102               M           20대   
22764    53376856         20221102               M           50대   
22765    53377393         20221102               F           50대   
22766    53377523         20221102               F           60대   

      ANSWRR_OC_AREA_NM HSHLD_INCOME_DGREE_NM  \
0                 광주광역시         300이상500만원 미만   
1                  전라남도              300만원 미만   
2                   경기도         300이상500만원 미만   
3                 대전광역시              300만원 미만   
4                   경기도         500이상700만원 미만   
...                 ...                   ...   
22762             서울특별시         300이상500만원 미만   
22763               경기도                   무응답   
22764               경기도         500이상700만원 미만   
22765             대구광역시         500이상700만원 미만   
22766               강원도              300만원 미만   

       WORKDAY_DAY_AVRG_LSR_TIME_VALUE  WKEND_DAY_AVRG_LSR_TIME_VALUE  \
0                                    2                              3   
1                                    3                              5   
2                                    3                             12   
3                                    3                              3   
4                                    3                             12   
...                                ...                            ...   
22762                                0                             10   
22763                                5                              9   
22764                                5                             12   
22765                                2                              0   
22766                                2                              2   

       ONE_WEEK_TOT_LSR_TIME_VALUE  LSR_TIME_REST_RCRT_USE_RATE  \
0                               16                           40   
1                               25                            0   
2                               39                           60   
3                               21                            0   
4                               39                           50   
...                            ...                          ...   
22762                           20                           10   
22763                           43                           50   
22764                           49                           40   
22765                           10                           30   
22766                           14                            0   

       LSR_TIME_HOBBY_USE_RATE  LSR_TIME_SELF_IMPT_USE_RATE  \
0                            0                            0   
1                            0                            0   
2                           40                            0   
3                            0                           25   
4                            0                           20   
...                        ...                          ...   
22762                       20                           30   
22763                        0                            0   
22764                       20                           15   
22765                       40                           10   
22766                       50                            0   

       LSR_TIME_TWDPSN_RLTN_FLWSP_USE_RATE  LSR_TIME_ETC_USE_RATE  
0                                       60                      0  
1                         

In [4]:
df = df[['income', 'gender', 'age', 'lsr_work', 'lsr_weekend', 'lsr_tot', 'rest', 'hobby', 'self', 'relation', 'etc']]

In [5]:
df

income gender  age  lsr_work  lsr_weekend  lsr_tot  rest  hobby  \
0      300이상500만원 미만      F  50대         2            3       16    40      0   
1           300만원 미만      M  60대         3            5       25     0      0   
2      300이상500만원 미만      F  30대         3           12       39    60     40   
3           300만원 미만      M  50대         3            3       21     0      0   
4      500이상700만원 미만      F  30대         3           12       39    50      0   
...              ...    ...  ...       ...          ...      ...   ...    ...   
22762  300이상500만원 미만      F  50대         0           10       20    10     20   
22763            무응답      M  20대         5            9       43    50      0   
22764  500이상700만원 미만      M  50대         5           12       49    40     20   
22765  500이상700만원 미만      F  50대         2            0       10    30     40   
22766       300만원 미만      F  60대         2            2       14     0     50   

       self  relation  etc  
0         0        60    0  
1         0        30   70  
2         0         0    0  
3        25        65   10  
4        20        30    0  
...     ...       ...  ...  
22762    30        20   20  
22763     0        50    0  
22764    15        25    0  
22765    10        20    0  
22766     0        50    0  

[22767 rows x 11 columns]

In [6]:
# 예측할 데이터

In [7]:
df2 = df[df['income'] == '무응답']

In [9]:
df2

income gender  age  lsr_work  lsr_weekend  lsr_tot  rest  hobby  self  \
54       무응답      F  20대         4           12       44    93      2     0   
88       무응답      F  50대         3            5       25    40     10    20   
90       무응답      F  20대         2            8       26    30      0    20   
116      무응답      F  50대         2            3       16    35     20    10   
196      무응답      M  30대         8           10       60    35      0    35   
...      ...    ...  ...       ...          ...      ...   ...    ...   ...   
22643    무응답      M  20대         6            9       48    69     30     0   
22672    무응답      F  60대         3            5       25    20     30    20   
22706    무응답      M  20대         2           10       30    20     10     0   
22708    무응답      F  20대         3            6       27    30     10    20   
22763    무응답      M  20대         5            9       43    50      0     0   

       relation  etc  
54            5    0  
88           30    0  
90           50    0  
116           5   30  
196          30    0  
...         ...  ...  
22643         1    0  
22672        10   20  
22706        70    0  
22708        40    0  
22763        50    0  

[1206 rows x 11 columns]

In [ ]:
# train + test 데이터

In [10]:
df = df[df['income'] != '무응답']

In [11]:
df

income gender  age  lsr_work  lsr_weekend  lsr_tot  rest  hobby  \
0      300이상500만원 미만      F  50대         2            3       16    40      0   
1           300만원 미만      M  60대         3            5       25     0      0   
2      300이상500만원 미만      F  30대         3           12       39    60     40   
3           300만원 미만      M  50대         3            3       21     0      0   
4      500이상700만원 미만      F  30대         3           12       39    50      0   
...              ...    ...  ...       ...          ...      ...   ...    ...   
22761       300만원 미만      M  40대         2            3       16    40     30   
22762  300이상500만원 미만      F  50대         0           10       20    10     20   
22764  500이상700만원 미만      M  50대         5           12       49    40     20   
22765  500이상700만원 미만      F  50대         2            0       10    30     40   
22766       300만원 미만      F  60대         2            2       14     0     50   

       self  relation  etc  
0         0        60    0  
1         0        30   70  
2         0         0    0  
3        25        65   10  
4        20        30    0  
...     ...       ...  ...  
22761    30         0    0  
22762    30        20   20  
22764    15        25    0  
22765    10        20    0  
22766     0        50    0  

[21561 rows x 11 columns]

In [12]:
df['income'].unique()

array(['300이상500만원 미만', '300만원 미만', '500이상700만원 미만', '700만원 이상'],
      dtype=object)

In [13]:
# X, y분리

In [14]:
X = df.loc[:, 'gender':'etc']

In [15]:
X

gender  age  lsr_work  lsr_weekend  lsr_tot  rest  hobby  self  \
0          F  50대         2            3       16    40      0     0   
1          M  60대         3            5       25     0      0     0   
2          F  30대         3           12       39    60     40     0   
3          M  50대         3            3       21     0      0    25   
4          F  30대         3           12       39    50      0    20   
...      ...  ...       ...          ...      ...   ...    ...   ...   
22761      M  40대         2            3       16    40     30    30   
22762      F  50대         0           10       20    10     20    30   
22764      M  50대         5           12       49    40     20    15   
22765      F  50대         2            0       10    30     40    10   
22766      F  60대         2            2       14     0     50     0   

       relation  etc  
0            60    0  
1            30   70  
2             0    0  
3            65   10  
4            30    0  
...         ...  ...  
22761         0    0  
22762        20   20  
22764        25    0  
22765        20    0  
22766        50    0  

[21561 rows x 10 columns]

In [16]:
y = df['income']

In [17]:
y

0        300이상500만원 미만
1             300만원 미만
2        300이상500만원 미만
3             300만원 미만
4        500이상700만원 미만
             ...      
22761         300만원 미만
22762    300이상500만원 미만
22764    500이상700만원 미만
22765    500이상700만원 미만
22766         300만원 미만
Name: income, Length: 21561, dtype: object

In [18]:
X['gender'].unique()

array(['F', 'M'], dtype=object)

In [19]:
X['age'].unique()

array(['50대', '60대', '30대', '40대', '20대'], dtype=object)

In [17]:
# one-hot encoding

In [21]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, MinMaxScaler
from sklearn.compose import ColumnTransformer

In [37]:
X

gender  age  lsr_work  lsr_weekend  lsr_tot  rest  hobby  self  \
0          F  50대         2            3       16    40      0     0   
1          M  60대         3            5       25     0      0     0   
2          F  30대         3           12       39    60     40     0   
3          M  50대         3            3       21     0      0    25   
4          F  30대         3           12       39    50      0    20   
...      ...  ...       ...          ...      ...   ...    ...   ...   
22761      M  40대         2            3       16    40     30    30   
22762      F  50대         0           10       20    10     20    30   
22764      M  50대         5           12       49    40     20    15   
22765      F  50대         2            0       10    30     40    10   
22766      F  60대         2            2       14     0     50     0   

       relation  etc  
0            60    0  
1            30   70  
2             0    0  
3            65   10  
4            30    0  
...         ...  ...  
22761         0    0  
22762        20   20  
22764        25    0  
22765        20    0  
22766        50    0  

[21561 rows x 10 columns]

In [29]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21561 entries, 0 to 22766
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   gender       21561 non-null  object
 1   age          21561 non-null  object
 2   lsr_work     21561 non-null  int64 
 3   lsr_weekend  21561 non-null  int64 
 4   lsr_tot      21561 non-null  int64 
 5   rest         21561 non-null  int64 
 6   hobby        21561 non-null  int64 
 7   self         21561 non-null  int64 
 8   relation     21561 non-null  int64 
 9   etc          21561 non-null  int64 
dtypes: int64(8), object(2)
memory usage: 1.8+ MB


In [39]:
ct = ColumnTransformer( [ ('encoder', OneHotEncoder(), [0, 1]) ],
                      # [(   이름,    트랜스포머,    컬럼 ) ]                 
                       remainder= 'passthrough')
        

In [40]:
X = ct.fit_transform(X)

In [41]:
X.shape

(21561, 15)

In [42]:
X[3]

array([ 0.,  1.,  0.,  0.,  0.,  1.,  0.,  3.,  3., 21.,  0.,  0., 25.,
       65., 10.])

In [43]:
X_scaler = MinMaxScaler()

In [44]:
X = X_scaler.fit_transform(X)

In [45]:
X

array([[1.  , 0.  , 0.  , ..., 0.  , 0.6 , 0.  ],
       [0.  , 1.  , 0.  , ..., 0.  , 0.3 , 0.7 ],
       [1.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       ...,
       [0.  , 1.  , 0.  , ..., 0.15, 0.25, 0.  ],
       [1.  , 0.  , 0.  , ..., 0.1 , 0.2 , 0.  ],
       [1.  , 0.  , 0.  , ..., 0.  , 0.5 , 0.  ]])

In [62]:
X.shape

(21561, 15)

In [46]:
y_encoder = LabelEncoder()

In [47]:
y = y_encoder.fit_transform(y)

In [51]:
y

array([1, 0, 1, ..., 2, 2, 0])

In [52]:
y.shape

(21561,)

In [ ]:
# 트레인테스트분리

In [53]:
from sklearn.model_selection import train_test_split

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [55]:
X_train.shape

(16170, 15)

In [56]:
X_test.shape

(5391, 15)

In [57]:
y_train.shape

(16170,)

In [58]:
y_test.shape

(5391,)

In [ ]:
# 모델링

In [59]:
from sklearn.tree import DecisionTreeClassifier

In [60]:
classifier = DecisionTreeClassifier()

In [61]:
classifier.fit(X_train, y_train)

DecisionTreeClassifier()

In [63]:
y_pred = classifier.predict(X_test)

In [64]:
y_pred

array([3, 3, 3, ..., 2, 0, 3])

In [65]:
y_test

array([3, 3, 1, ..., 2, 2, 0])

In [66]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [67]:
confusion_matrix(y_test, y_pred)

array([[472, 467, 264, 248],
       [482, 568, 334, 323],
       [268, 361, 236, 231],
       [319, 365, 224, 229]], dtype=int64)

In [68]:
accuracy_score(y_test, y_pred)

0.279168985345947

In [69]:
y_pred.shape

(5391,)

In [70]:
y_test.shape

(5391,)

In [ ]:
# LogisticRegression

In [71]:
from sklearn.linear_model import LogisticRegression

In [72]:
classifier2 = LogisticRegression(random_state=1)

In [73]:
classifier2.fit(X_train, y_train)

LogisticRegression(random_state=1)

In [74]:
y_pred = classifier2.predict(X_test)

In [75]:
accuracy_score(y_test, y_pred)

0.33926915229085514

In [ ]:
# 서포트벡터머신

In [76]:
from sklearn.svm import SVC

In [77]:
classifier3 = SVC(kernel='rbf', random_state=1)

In [78]:
classifier3.fit(X_train, y_train)

SVC(random_state=1)

In [79]:
y_pred = classifier3.predict(X_test)

In [80]:
confusion_matrix(y_test, y_pred)

array([[ 499,  827,    0,  125],
       [ 393, 1149,    0,  165],
       [ 196,  738,    0,  162],
       [ 249,  672,    0,  216]], dtype=int64)

In [81]:
accuracy_score(y_test, y_pred)

0.3457614542756446

In [ ]:
# 랜덤포레스트

In [82]:
from sklearn.ensemble import RandomForestClassifier

In [83]:
classifier4 = RandomForestClassifier()

In [84]:
classifier4.fit(X_train, y_train)

RandomForestClassifier()

In [85]:
y_pred = classifier4.predict(X_test)

In [86]:
confusion_matrix(y_test, y_pred)

array([[507, 515, 191, 238],
       [465, 686, 267, 289],
       [253, 416, 197, 230],
       [301, 402, 180, 254]], dtype=int64)

In [87]:
accuracy_score(y_test, y_pred)

0.30495269894268223