In [3]:
import pandas as pd
import numpy as np

In [4]:
df_origin = pd.read_csv('data/df_origin.csv', index_col=0)

df = df_origin.copy()
# 컬럼명 변경
df = df.rename(columns={'EXAMIN_BEGIN_DE':'date', 
                    'SEXDSTN_FLAG_CD': 'gender',
                    'AGRDE_FLAG_NM': 'age',
                    'ANSWRR_OC_AREA_NM': 'area',
                    'HSHLD_INCOME_DGREE_NM': 'income',
                    'WORKDAY_DAY_AVRG_LSR_TIME_VALUE': 'lsr_work',
                    'WKEND_DAY_AVRG_LSR_TIME_VALUE': 'lsr_weekend',
                    'ONE_WEEK_TOT_LSR_TIME_VALUE': 'lsr_tot',
                    'LSR_TIME_REST_RCRT_USE_RATE': 'rest',
                    'LSR_TIME_HOBBY_USE_RATE': 'hobby',
                    'LSR_TIME_SELF_IMPT_USE_RATE': 'self',
                    'LSR_TIME_TWDPSN_RLTN_FLWSP_USE_RATE': 'relation',
                    'LSR_TIME_ETC_USE_RATE': 'etc'
                    })
# 조사날짜 컬럼 타입변경
df['date'] = pd.to_datetime(df['date'], format='%Y%m%d').dt.strftime('%Y-%m-%d')

In [5]:
df = df[['income', 'gender', 'age', 'lsr_work', 'lsr_weekend', 'lsr_tot', 'rest', 'hobby', 'self', 'relation', 'etc']]

In [6]:
df

income gender  age  lsr_work  lsr_weekend  lsr_tot  rest  hobby  \
0      300이상500만원 미만      M  60대         8           12       64    50     30   
1           300만원 미만      M  20대         2            4       18    50     10   
2           700만원 이상      F  60대         8            6       52    30     20   
3      500이상700만원 미만      F  50대         4            6       32    15     15   
4           300만원 미만      F  50대         5            5       35    20     20   
...              ...    ...  ...       ...          ...      ...   ...    ...   
12584  300이상500만원 미만      F  50대         0           10       20    10     20   
12585            무응답      M  20대         5            9       43    50      0   
12586  500이상700만원 미만      M  50대         5           12       49    40     20   
12587  500이상700만원 미만      F  50대         2            0       10    30     40   
12588       300만원 미만      F  60대         2            2       14     0     50   

       self  relation  etc  
0         0        20    0  
1        10        30    0  
2        40        10    0  
3        20        50    0  
4        20        20   20  
...     ...       ...  ...  
12584    30        20   20  
12585     0        50    0  
12586    15        25    0  
12587    10        20    0  
12588     0        50    0  

[12589 rows x 11 columns]

In [7]:
df2 = df[df['income'] == '무응답']

In [8]:
df2

income gender  age  lsr_work  lsr_weekend  lsr_tot  rest  hobby  self  \
44       무응답      F  30대         3            8       31    10     10    50   
54       무응답      F  20대         3            3       21    10     70    10   
57       무응답      F  20대         1            4       13     5     40     5   
58       무응답      F  40대         2            5       20    50     20     5   
64       무응답      M  20대        10           10       70    31     19    13   
...      ...    ...  ...       ...          ...      ...   ...    ...   ...   
12465    무응답      M  20대         6            9       48    69     30     0   
12494    무응답      F  60대         3            5       25    20     30    20   
12528    무응답      M  20대         2           10       30    20     10     0   
12530    무응답      F  20대         3            6       27    30     10    20   
12585    무응답      M  20대         5            9       43    50      0     0   

       relation  etc  
44           30    0  
54           10    0  
57           50    0  
58           25    0  
64           13   24  
...         ...  ...  
12465         1    0  
12494        10   20  
12528        70    0  
12530        40    0  
12585        50    0  

[711 rows x 11 columns]

In [9]:
df = df[df['income'] != '무응답']

In [10]:
df

income gender  age  lsr_work  lsr_weekend  lsr_tot  rest  hobby  \
0      300이상500만원 미만      M  60대         8           12       64    50     30   
1           300만원 미만      M  20대         2            4       18    50     10   
2           700만원 이상      F  60대         8            6       52    30     20   
3      500이상700만원 미만      F  50대         4            6       32    15     15   
4           300만원 미만      F  50대         5            5       35    20     20   
...              ...    ...  ...       ...          ...      ...   ...    ...   
12583       300만원 미만      M  40대         2            3       16    40     30   
12584  300이상500만원 미만      F  50대         0           10       20    10     20   
12586  500이상700만원 미만      M  50대         5           12       49    40     20   
12587  500이상700만원 미만      F  50대         2            0       10    30     40   
12588       300만원 미만      F  60대         2            2       14     0     50   

       self  relation  etc  
0         0        20    0  
1        10        30    0  
2        40        10    0  
3        20        50    0  
4        20        20   20  
...     ...       ...  ...  
12583    30         0    0  
12584    30        20   20  
12586    15        25    0  
12587    10        20    0  
12588     0        50    0  

[11878 rows x 11 columns]

In [11]:
df['income'].unique()

array(['300이상500만원 미만', '300만원 미만', '700만원 이상', '500이상700만원 미만'],
      dtype=object)

In [12]:
# X, y분리

In [13]:
X = df.loc[:, 'gender':'etc']

In [14]:
X

gender  age  lsr_work  lsr_weekend  lsr_tot  rest  hobby  self  \
0          M  60대         8           12       64    50     30     0   
1          M  20대         2            4       18    50     10    10   
2          F  60대         8            6       52    30     20    40   
3          F  50대         4            6       32    15     15    20   
4          F  50대         5            5       35    20     20    20   
...      ...  ...       ...          ...      ...   ...    ...   ...   
12583      M  40대         2            3       16    40     30    30   
12584      F  50대         0           10       20    10     20    30   
12586      M  50대         5           12       49    40     20    15   
12587      F  50대         2            0       10    30     40    10   
12588      F  60대         2            2       14     0     50     0   

       relation  etc  
0            20    0  
1            30    0  
2            10    0  
3            50    0  
4            20   20  
...         ...  ...  
12583         0    0  
12584        20   20  
12586        25    0  
12587        20    0  
12588        50    0  

[11878 rows x 10 columns]

In [15]:
y = df['income']

In [16]:
y

0        300이상500만원 미만
1             300만원 미만
2             700만원 이상
3        500이상700만원 미만
4             300만원 미만
             ...      
12583         300만원 미만
12584    300이상500만원 미만
12586    500이상700만원 미만
12587    500이상700만원 미만
12588         300만원 미만
Name: income, Length: 11878, dtype: object

In [17]:
y = y.to_frame()

In [18]:
X['gender'].unique()

array(['M', 'F'], dtype=object)

In [19]:
X['age'].unique()

array(['60대', '20대', '50대', '30대', '40대'], dtype=object)

In [ ]:
# one-hot encoding

In [20]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer

In [21]:
X_ct = ColumnTransformer( [ ('encoder', OneHotEncoder(), [0, 1]) ],
                      # [(   이름,    트랜스포머,    컬럼 ) ]                 
                       remainder= 'passthrough')
                       # remainder = 'drop' : 변환하지 않는 컬럼을 모두 버린다.
                       # remainder = 'passthrough : 변환하지 않는 컬럼을 그대로 놔둔다.

In [22]:
X = X_ct.fit_transform(X)

In [23]:
X.shape

(11878, 15)

In [24]:
X[3]

array([ 1.,  0.,  0.,  0.,  0.,  1.,  0.,  4.,  6., 32., 15., 15., 20.,
       50.,  0.])

In [25]:
y_encoder = LabelEncoder()

In [29]:
y = y_encoder.fit_transform(y)

In [30]:
y

array([1, 0, 3, ..., 2, 2, 0], dtype=int64)

In [ ]:
# 트레인테스트분리

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25,
                                                   random_state=1)

In [34]:
X_train.shape

(8908, 15)

In [35]:
X_test.shape

(2970, 15)

In [36]:
y_train.shape

(8908,)

In [37]:
y_test.shape

(2970,)

In [ ]:
# 모델링

In [38]:
from sklearn.tree import DecisionTreeClassifier

In [39]:
classifier = DecisionTreeClassifier(random_state=1)

In [40]:
classifier.fit(X_train, y_train)

DecisionTreeClassifier(random_state=1)

In [41]:
y_pred = classifier.predict(X_test)

In [42]:
y_pred

array([0, 3, 1, ..., 0, 3, 1], dtype=int64)

In [43]:
y_test

array([3, 0, 0, ..., 3, 2, 1], dtype=int64)

In [44]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [45]:
cm = confusion_matrix(y_test, y_pred)

In [46]:
cm

array([[254, 243, 153, 148],
       [249, 300, 203, 176],
       [167, 192, 133, 143],
       [148, 211, 115, 135]], dtype=int64)

In [50]:
accuracy_score(y_test, y_pred)

0.2767676767676768

In [49]:
y_pred.shape

(2970,)

In [48]:
y_test.shape

(2970,)