In [1]:
import pandas as pd
import numpy as np

In [2]:
df_origin = pd.read_csv('data/df_origin.csv', index_col=0)

df = df_origin.copy()
# 컬럼명 변경
df = df.rename(columns={'EXAMIN_BEGIN_DE':'date', 
                    'SEXDSTN_FLAG_CD': 'gender',
                    'AGRDE_FLAG_NM': 'age',
                    'ANSWRR_OC_AREA_NM': 'area',
                    'HSHLD_INCOME_DGREE_NM': 'income',
                    'WORKDAY_DAY_AVRG_LSR_TIME_VALUE': 'lsr_work',
                    'WKEND_DAY_AVRG_LSR_TIME_VALUE': 'lsr_weekend',
                    'ONE_WEEK_TOT_LSR_TIME_VALUE': 'lsr_tot',
                    'LSR_TIME_REST_RCRT_USE_RATE': 'rest',
                    'LSR_TIME_HOBBY_USE_RATE': 'hobby',
                    'LSR_TIME_SELF_IMPT_USE_RATE': 'self',
                    'LSR_TIME_TWDPSN_RLTN_FLWSP_USE_RATE': 'relation',
                    'LSR_TIME_ETC_USE_RATE': 'etc'
                    })
# 조사날짜 컬럼 타입변경
df['date'] = pd.to_datetime(df['date'], format='%Y%m%d').dt.strftime('%Y-%m-%d')

In [3]:
df = df[['income', 'gender', 'age', 'lsr_work', 'lsr_weekend', 'lsr_tot', 'rest', 'hobby', 'self', 'relation', 'etc']]

In [4]:
df

income gender  age  lsr_work  lsr_weekend  lsr_tot  rest  hobby  \
0      300이상500만원 미만      M  60대         8           12       64    50     30   
1           300만원 미만      M  20대         2            4       18    50     10   
2           700만원 이상      F  60대         8            6       52    30     20   
3      500이상700만원 미만      F  50대         4            6       32    15     15   
4           300만원 미만      F  50대         5            5       35    20     20   
...              ...    ...  ...       ...          ...      ...   ...    ...   
12058       300만원 미만      F  50대         2            4       18    10     80   
12059  300이상500만원 미만      M  50대         1            2        9    15     35   
12060       700만원 이상      M  20대         2            7       24    50     20   
12061       300만원 미만      M  50대         1            2        9    70     30   
12062       300만원 미만      F  30대         2           10       30    70     10   

       self  relation  etc  
0         0        20    0  
1        10        30    0  
2        40        10    0  
3        20        50    0  
4        20        20   20  
...     ...       ...  ...  
12058     0        10    0  
12059    30        20    0  
12060    20        10    0  
12061     0         0    0  
12062    15         5    0  

[12063 rows x 11 columns]

In [5]:
df2 = df[df['income'] == '무응답']

In [6]:
df2

income gender  age  lsr_work  lsr_weekend  lsr_tot  rest  hobby  self  \
44       무응답      F  30대         3            8       31    10     10    50   
54       무응답      F  20대         3            3       21    10     70    10   
57       무응답      F  20대         1            4       13     5     40     5   
58       무응답      F  40대         2            5       20    50     20     5   
64       무응답      M  20대        10           10       70    31     19    13   
...      ...    ...  ...       ...          ...      ...   ...    ...   ...   
11968    무응답      F  40대        15            0       75     0     50     0   
11994    무응답      M  20대         3            6       27    20      0    60   
12021    무응답      F  30대         8            8       56    70      0     5   
12053    무응답      M  20대         2            6       22    70      0     0   
12056    무응답      F  20대         3            0       15    20      0     0   

       relation  etc  
44           30    0  
54           10    0  
57           50    0  
58           25    0  
64           13   24  
...         ...  ...  
11968        50    0  
11994        20    0  
12021        25    0  
12053        10   20  
12056        80    0  

[687 rows x 11 columns]

In [7]:
df = df[df['income'] != '무응답']

In [8]:
df

income gender  age  lsr_work  lsr_weekend  lsr_tot  rest  hobby  \
0      300이상500만원 미만      M  60대         8           12       64    50     30   
1           300만원 미만      M  20대         2            4       18    50     10   
2           700만원 이상      F  60대         8            6       52    30     20   
3      500이상700만원 미만      F  50대         4            6       32    15     15   
4           300만원 미만      F  50대         5            5       35    20     20   
...              ...    ...  ...       ...          ...      ...   ...    ...   
12058       300만원 미만      F  50대         2            4       18    10     80   
12059  300이상500만원 미만      M  50대         1            2        9    15     35   
12060       700만원 이상      M  20대         2            7       24    50     20   
12061       300만원 미만      M  50대         1            2        9    70     30   
12062       300만원 미만      F  30대         2           10       30    70     10   

       self  relation  etc  
0         0        20    0  
1        10        30    0  
2        40        10    0  
3        20        50    0  
4        20        20   20  
...     ...       ...  ...  
12058     0        10    0  
12059    30        20    0  
12060    20        10    0  
12061     0         0    0  
12062    15         5    0  

[11376 rows x 11 columns]

In [9]:
df['income'].unique()

array(['300이상500만원 미만', '300만원 미만', '700만원 이상', '500이상700만원 미만'],
      dtype=object)

In [10]:
# X, y분리

In [11]:
X = df.loc[:, 'gender':'etc']

In [12]:
X

gender  age  lsr_work  lsr_weekend  lsr_tot  rest  hobby  self  \
0          M  60대         8           12       64    50     30     0   
1          M  20대         2            4       18    50     10    10   
2          F  60대         8            6       52    30     20    40   
3          F  50대         4            6       32    15     15    20   
4          F  50대         5            5       35    20     20    20   
...      ...  ...       ...          ...      ...   ...    ...   ...   
12058      F  50대         2            4       18    10     80     0   
12059      M  50대         1            2        9    15     35    30   
12060      M  20대         2            7       24    50     20    20   
12061      M  50대         1            2        9    70     30     0   
12062      F  30대         2           10       30    70     10    15   

       relation  etc  
0            20    0  
1            30    0  
2            10    0  
3            50    0  
4            20   20  
...         ...  ...  
12058        10    0  
12059        20    0  
12060        10    0  
12061         0    0  
12062         5    0  

[11376 rows x 10 columns]

In [13]:
y = df['income']

In [14]:
y

0        300이상500만원 미만
1             300만원 미만
2             700만원 이상
3        500이상700만원 미만
4             300만원 미만
             ...      
12058         300만원 미만
12059    300이상500만원 미만
12060         700만원 이상
12061         300만원 미만
12062         300만원 미만
Name: income, Length: 11376, dtype: object

In [15]:
X['gender'].unique()

array(['M', 'F'], dtype=object)

In [16]:
X['age'].unique()

array(['60대', '20대', '50대', '30대', '40대'], dtype=object)

In [17]:
# one-hot encoding

In [18]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, MinMaxScaler
from sklearn.compose import ColumnTransformer

In [19]:
X_ct = ColumnTransformer( [ ('encoder', OneHotEncoder(), [0, 1]) ],
                      # [(   이름,    트랜스포머,    컬럼 ) ]                 
                       remainder= 'passthrough')
                       # remainder = 'drop' : 변환하지 않는 컬럼을 모두 버린다.
                       # remainder = 'passthrough : 변환하지 않는 컬럼을 그대로 놔둔다.

In [20]:
X = X_ct.fit_transform(X)

In [21]:
X.shape

(11376, 15)

In [22]:
X[3]

array([ 1.,  0.,  0.,  0.,  0.,  1.,  0.,  4.,  6., 32., 15., 15., 20.,
       50.,  0.])

In [24]:
X_scaler = MinMaxScaler()

In [25]:
X = X_scaler.fit_transform(X)

In [26]:
X

array([[0.  , 1.  , 0.  , ..., 0.  , 0.2 , 0.  ],
       [0.  , 1.  , 1.  , ..., 0.1 , 0.3 , 0.  ],
       [1.  , 0.  , 0.  , ..., 0.4 , 0.1 , 0.  ],
       ...,
       [0.  , 1.  , 1.  , ..., 0.2 , 0.1 , 0.  ],
       [0.  , 1.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  , ..., 0.15, 0.05, 0.  ]])

In [27]:
y_encoder = LabelEncoder()

In [28]:
y = y_encoder.fit_transform(y)

In [29]:
y

array([1, 0, 3, ..., 3, 0, 0])

In [30]:
y.shape

(11376,)

In [ ]:
# 트레인테스트분리

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [33]:
X_train.shape

(8532, 15)

In [34]:
X_test.shape

(2844, 15)

In [35]:
y_train.shape

(8532,)

In [36]:
y_test.shape

(2844,)

In [ ]:
# 모델링

In [37]:
from sklearn.tree import DecisionTreeClassifier

In [38]:
classifier = DecisionTreeClassifier()

In [39]:
classifier.fit(X_train, y_train)

DecisionTreeClassifier()

In [40]:
y_pred = classifier.predict(X_test)

In [41]:
y_pred

array([0, 2, 1, ..., 0, 2, 1])

In [42]:
y_test

array([1, 1, 1, ..., 2, 0, 3])

In [43]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [44]:
cm = confusion_matrix(y_test, y_pred)

In [45]:
cm

array([[226, 239, 143, 135],
       [278, 299, 182, 155],
       [158, 184, 132, 111],
       [155, 171, 145, 131]], dtype=int64)

In [46]:
accuracy_score(y_test, y_pred)

0.2770745428973277

In [42]:
y_pred.shape

(2844,)

In [43]:
y_test.shape

(2844,)

In [ ]:
# LogisticRegression

In [47]:
from sklearn.linear_model import LogisticRegression

In [48]:
classifier2 = LogisticRegression(random_state=1)

In [49]:
classifier2.fit(X_train, y_train)

LogisticRegression(random_state=1)

In [50]:
y_pred = classifier2.predict(X_test)

In [51]:
accuracy_score(y_test, y_pred)

0.3540787623066104

In [ ]:
# 서포트벡터머신

In [52]:
from sklearn.svm import SVC

In [54]:
classifier3 = SVC(kernel='rbf', random_state=1)

In [55]:
classifier3.fit(X_train, y_train)

SVC(random_state=1)

In [56]:
y_pred = classifier3.predict(X_test)

In [57]:
confusion_matrix(y_test, y_pred)

array([[300, 401,   5,  37],
       [231, 609,  12,  62],
       [128, 396,  13,  48],
       [159, 340,  17,  86]], dtype=int64)

In [58]:
accuracy_score(y_test, y_pred)

0.35443037974683544

In [ ]:
# 랜덤포레스트

In [59]:
from sklearn.ensemble import RandomForestClassifier

In [61]:
classifier4 = RandomForestClassifier()

In [62]:
classifier4.fit(X_train, y_train)

RandomForestClassifier()

In [63]:
y_pred = classifier4.predict(X_test)

In [64]:
confusion_matrix(y_test, y_pred)

array([[270, 271, 102, 100],
       [298, 342, 132, 142],
       [157, 242,  92,  94],
       [170, 186, 116, 130]], dtype=int64)

In [65]:
accuracy_score(y_test, y_pred)

0.29324894514767935